import { ProviderAdm } from "./providers"
import { Roboto } from "next/font/google";
import localFont from 'next/font/local'
import './globals.css'

const roboto = Roboto({ subsets: ["latin"], weight: ["300"], variable: '--font-roboto' })
const draco = localFont({
  src: './fonts/Draco.otf',
  variable: '--font-draco'
})
const decking = localFont({
  src: './fonts/Decking.otf',
  variable: '--font-decking'
})
const galantic = localFont({
  src: './fonts/GalanticItalic.otf',
  variable: '--font-galantic'
})



export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  
  
  return (
    <html lang="pt-BR">
      <body className={`${draco.variable} ${decking.variable} ${galantic.variable} ${roboto.variable}`}>
        <section>
          <ProviderAdm>
            {children}
          </ProviderAdm>
        </section>
      </body>
    </html>
  )
}
